esphome:
  name: dfplayerdevice
  friendly_name: DFPlayerDevice

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Dfplayerdevice Fallback Hotspot"
    password: "HsMAxzaDr4xg"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "<insert your key here>"
  
  services:
    # Play specific MP3 file
    - service: play_mp3
      variables:
        file_number: int
      then:
        - dfplayer.play_mp3:
            file: !lambda 'return file_number;'
    
    # Set volume (0-30)
    - service: set_volume
      variables:
        volume: int
      then:
        - dfplayer.set_volume: !lambda 'return volume;'
    
    # Stop playback
    - service: stop_playback
      then:
        - dfplayer.stop

# OTA updates
ota:
  - platform: esphome
    password: "7cf88fccb756ef4fce2cdf009f784eef"

# Web server
web_server:
  port: 80

# UART configuration for DFPlayer
uart:
  tx_pin: GPIO20
  rx_pin: GPIO21
  baud_rate: 9600

# DFPlayer configuration
dfplayer:
  id: dfplayerdevice
  on_finished_playback:
    then:
      - logger.log: "Sound finished playing"

# Buttons to play specific sounds
button:
  - platform: template
    name: "Play Sound 1"
    on_press:
      - dfplayer.play_mp3: 1
  
  - platform: template
    name: "Play Sound 2"
    on_press:
      - dfplayer.play_mp3: 2
  
  - platform: template
    name: "Play Sound 3"
    on_press:
      - dfplayer.play_mp3: 3
  
  - platform: template
    name: "Play Sound 4"
    on_press:
      - dfplayer.play_mp3: 4
  
  - platform: template
    name: "Play Sound 5"
    on_press:
      - dfplayer.play_mp3: 5
  
  - platform: template
    name: "Play Sound 6"
    on_press:
      - dfplayer.play_mp3: 6
  
  - platform: template
    name: "Play Sound 7"
    on_press:
      - dfplayer.play_mp3: 7
  
  - platform: template
    name: "Play Sound 8"
    on_press:
      - dfplayer.play_mp3: 8
  
  - platform: template
    name: "Stop Playback"
    on_press:
      - dfplayer.stop

# Volume control
number:
  - platform: template
    name: "Volume"
    id: volume_control
    min_value: 0
    max_value: 30
    step: 1
    initial_value: 20
    optimistic: true
    restore_value: true
    set_action:
      then:
        - dfplayer.set_volume: !lambda 'return (int)x;'
